const CONFIG = {
    siteName: "Tư Ngữ Audio",
    avatar: "./avt.jpg",
    rootPath: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main"
};

// Mock Data
const LIBRARY = [
    {
        id: 1,
        folderName: "ChinhPhucDoiThuDenNghien",
        title: "Chinh Phục Đối Thủ Đến Nghiện",
        author: "A Sấu A",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/ChinhPhucDoiThuDenNghien/cover.jpg",
        desc: "Hai người có tiếng cả đời không qua lại với nhau, không chỉ là cạnh tranh trong việc học hành mà còn nhìn đối phương không vừa mắt.\nNhưng không ai biết, trong âm thầm, bọn họ thường xuyên ra vào Như Gia thuê phòng bắn pháo.\nLục Hoài Chuẩn: Bạn gái người khác ở trên giường đều là xoắn xuýt lấy dương vật của bạn trai, lẳng lơ hăng say kêu: “A, dương vật của chồng lớn quá, làm người ta thật sướng.”\nBạn gái của tôi lại không giống vậy, cô ấy ở trên người tôi vặn vẹo hăng say và hỏi: “Đáp án đề tự luận cuối cùng trong bài thi toán học của anh là gì?”",
        tracks: [
            { title: "Chương 1 - 20 (1)", fileName: "c1-20 (1).mp3" },
            { title: "Chương 1 - 20 (2)", fileName: "c1-20 (2).mp3" },
            { title: "Chương 21 - 40 (1)", fileName: "c21-40 (1).mp3" },
            { title: "Chương 21 - 40 (2)", fileName: "c21-40 (2).mp3" },
            { title: "Chương 41 - 60 (1)", fileName: "c41-60 (1).mp3" },
            { title: "Chương 41 - 60 (2)", fileName: "c41-60 (2).mp3" },
            { title: "Chương 61 - 70 (Hết)", fileName: "c61-70.mp3" }
        ]
    },
    {
        id: 2,
        folderName: "MatCaVaChauNgoc",
        title: "Mắt Cá Và Châu Ngọc",
        author: "Tể Lệ Liệp Thủ",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/MatCaVaChauNgoc/cover.jpg",
        desc: "Hàn Trân và Quý Đình Tông là người thuộc hai tầng lớp khác nhau.\nLần đầu gặp anh, cô là người vợ bình phong vừa thoát khỏi một cuộc hôn nhân lừa dối, trong tình cảnh thảm hại, cô vô tình chọc vào nhân vật quyền cao chức trọng này.\nThế rồi mới vỡ lẽ, anh không phải một vị Phật vô dục vô cầu, mà là một con quỷ đắm chìm trong bể dục.\n\n(Thư ký trưởng Tỉnh ủy và Người dẫn chương trình, nam hơn nữ 15 tuổi)",
        tracks: [
            { title: "Chương 1 - 20 (1)", fileName: "c1-20 (1).mp3" },
            { title: "Chương 1 - 20 (2)", fileName: "c1-20 (2).mp3" },
            { title: "Chương 21 - 40", fileName: "c21-40.mp3" },
            { title: "Chương 41 - 60 (1)", fileName: "c41-60 (1).mp3" },
            { title: "Chương 41 - 60 (2)", fileName: "c41-60 (2).mp3" },
            { title: "Chương 61 - 80 (1)", fileName: "c61-80 (1).mp3" },
            { title: "Chương 61 - 80 (2)", fileName: "c61-80 (2).mp3" },
            { title: "Chương 81 - 100 (1)", fileName: "c81-100 (1).mp3" },
            { title: "Chương 81 - 100 (Hết)", fileName: "c81-100 (2).mp3" },
        ]
    },
    {
        id: 3,
        folderName: "VanNe",
        title: "Vân Nê",
        author: "Thanh Đăng",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/VanNe/cover.jpg",
        desc: "Trần Kiều chưa từng nghĩ sẽ có một ngày ác ma vươn nanh vuốt về phía cô... Bị lừa, bị bắt cóc, bị bán, bị đưa vào núi sâu, ở một nơi mà cô có dùng cả đời cũng không thể thoát được. Người đàn ông kia bức bách cô, giam cầm cô, mỗi đêm đều lăn lộn khiến cô sống không bằng chết. Trần Kiều nghĩ, dù có phải chết, cô cũng phải chạy thoát khỏi nơi quái quỷ này...\nLý Tồn Căn yêu chết người vợ nhỏ mà anh mua về, anh đào tim, đào phổi, thương cô sủng cô, cũng không có cách nào đổi lấy một nụ cười của cô. Chỉ khi dùng hết sức lực 'muốn' Trần Kiều, anh mới có thể nhìn thấy được một chút diễm lệ từ cô.\nLý Tồn Căn đỏ mắt, bóp chặt eo cô, “A Kiều, chúng ta phải bên nhau, cả đời.” Cô cắn răng ức chế rên rỉ, “Mơ đi!”\n\nLời tác giả:\n[ thương sủng, nam soái nữ mỹ, có cưỡng bức! ]\n[ đừng bị văn án dọa, nam chính là liếm cẩu, liếm đến cuối cùng, cần cái gì có cái đó! ]",
        tracks: [
            { title: "Chương 1 - 20 (1)", fileName: "c1-20 (1).mp3" },
            { title: "Chương 1 - 20 (2)", fileName: "c1-20 (2).mp3" },
            { title: "Chương 21 - 40 (1)", fileName: "c21-40 (1).mp3" },
            { title: "Chương 21 - 40 (2)", fileName: "c21-40 (2).mp3" },
            { title: "Chương 41 - 60 (1)", fileName: "c41-60 (1).mp3" },
            { title: "Chương 41 - 60 (2)", fileName: "c41-60 (2).mp3" },
            { title: "Chương 61 - 76 (1)", fileName: "c61-76 (1).mp3" },
            { title: "Chương 61 - 76 (2)", fileName: "c61-76 (2).mp3" },
            { title: "Chương 61 - 76 (Hết)", fileName: "c61-76 (3).mp3" },
        ]
    },
    {
        id: 4,
        folderName: "LucDuThanhMenDuTich",
        title: "Lục Dư Thành Mến Du Tích",
        author: "Bàn Bàn Quất",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/LucDuThanhMenDuTich/cover.jpg",
        desc: "Thiếu nữ đáng yêu vẻ ngoài ngoan ngoãn x học trưởng tiêu chuẩn vừa ngầu vừa manh\n\n“Anh có thể làm bạn giường cả đời của em, nhưng cũng muốn đeo nhẫn cho em cùng em đi hết quãng đời còn lại.”\n“Là tự em đến đây, vậy tại sao tôi phải buông tha để em đi?”\n“Hắn muốn nghe cô rên rỉ, muốn nghe cô cầu xin hắn, muốn nghe cô khóc dưới thân mình…”\n\nĐoạn ngắn 1:\nDu Tích vặn vẹo: “Anh là biến thái sao? Mua nhiều quần áo kỳ quái như vậy làm gì? Anh có phải đã lên kế hoạch từ lâu rồi hay không!”\n“Đúng vậy.” Lục Dư Thành vuốt ve một cái quần lót nhỏ trong suốt: “Muốn cùng em làm tình trong khi mặc những bộ đồ này. Mặc đồng phục, cột dây trói lại, mặc đến nửa kín nửa hở, đều muốn hết.”\n\nĐoạn ngắn 2:\nTay Du Tích chống lên khuôn ngực của người đàn ông: “Tôm hùm đất…. Em muốn ăn tôm hùm đất….” Cô đáng thương nhìn Lục Dư Thành: “Em đói quá.”\nLục Dư Thành bóp lấy bầu ngực đầy đặn của thiếu nữ, lưu manh nói: “Em no.”",
        tracks: [
            { title: "Chương 1 - 18 (Hết)", fileName: "c1-18.mp3" },
        ]
    },
    {
        id: 5,
        folderName: "HeThongSungPhi",
        title: "Hệ Thống: Sủng Phi Biết Làm Nũng Tốt Số Nhất",
        author: "Tương Tư Phong Tử Thái Tử Phi",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/HeThongSungPhi/cover.jpg",
        desc: "Gia Ý phúc mỏng, Tạ Yến ơn trạch, rất tương xứng\n\nNữ chủ trọng sinh thân kiều thể nhược vì tồn tại, trăm phương nghìn kế làm nũng bán si tích cóp ân sủng của đế vương để kéo dài phúc trạch.\n---------------\nNữ chủ: tích cóp tích cóp tích cóp\nNam chủ: sủng sủng sủng",
        tracks: [
            { title: "Chương 1 - 10", fileName: "c1-10.mp3" },
            { title: "Chương 11 - 20", fileName: "c11-20.mp3" },
            { title: "Chương 21 - 30", fileName: "c21-30.mp3" },
            { title: "Chương 31 - 40", fileName: "c31-40.mp3" },
            { title: "Chương 41 - 50", fileName: "c41-50.mp3" },
            { title: "Chương 51 - 60", fileName: "c51-60.mp3" },
            { title: "Chương 61 - 70", fileName: "c61-70.mp3" },
            { title: "Chương 71 - 80", fileName: "c71-80.mp3" },
            { title: "Chương 81 - 90", fileName: "c81-90.mp3" },
            { title: "Chương 91 - 100", fileName: "c91-100.mp3" },
            { title: "Chương 101 - 110", fileName: "c101-110.mp3" },
            { title: "Chương 111 - 120", fileName: "c111-120.mp3" },
            { title: "Chương 121 - 130", fileName: "c121-130.mp3" },
            { title: "Chương 131 - 140", fileName: "c131-140.mp3" },
            { title: "Chương 141 - 153", fileName: "c141-153.mp3" },
            { title: "Ngoại Truyện 1 - 5 (Hết)", fileName: "nt1-5.mp3" },
        ]
    },
    {
        id: 6,
        folderName: "AnhDenHoaLe",
        title: "Ánh Đèn Hoa Lệ",
        author: "Phất Hà Lão Yêu",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/AnhDenHoaLe/cover.jpg",
        desc: "Ở một góc phố đèn đỏ tại Vũ Hán có một tiệm trang điểm tên Trân Trân, chủ tiệm Giang Ánh Nghê tuy dữ dằn nhưng lại có tay nghề rất đỉnh.\nVào sinh nhật 19 tuổi, Giang Ánh Nghê tới trường lái ghi danh.\n“Học số sàn hay số tự động?”\nNgười đàn ông ngước lên nhìn cô gái trẻ trang điểm rất đậm: “Đã thành niên chưa?”\n“19.”\nGiang Ánh Nghê đặt thẻ căn cước công dân của mình lên bài đánh “rầm” một tiếng, lạnh lùng nhìn người đàn ông kia, mới hay ông chú này chính là một vị khách quen của khu phố đèn đỏ...\n“Số sàn 3000 tệ, bao dạy ba năm.” Rồi anh ta tỉnh bơ nói: “Trả bằng quét mã Alipay hoặc Wechat.”\n“Bớt chút được không?” Thái độ của cô rất đỗi ngang ngược.\n“Không được.” Anh lại liếc nhìn cô, “Về nhà bàn bạc với bố mẹ đi, xong hẵng tới ghi danh.”\n“Em không có bố mẹ.”\nGiang Ánh Nghê thôi trả giá, vừa quét mã trả tiền vừa hỏi: “Thực hành ai dạy thế?”\n“Em muốn ai dạy?” Anh nói: “Chỗ tôi có sáu giáo viên.”\nCô đáp: “Em muốn anh.”\nAnh nhướng mày, “Tôi là ông chủ, lười dạy lắm.”\n“Anh có dạy không thì bảo?” Giang Ánh Nghê hất cằm hỏi.\nAnh phì cười: “Có thể cân nhắc.”",
        tracks: [
            { title: "Chương 1 - 5", fileName: "c1-5.mp3" },
            { title: "Chương 6 - 10", fileName: "c6-10.mp3" },
            { title: "Chương 11 - 15", fileName: "c11-15.mp3" },
            { title: "Chương 16 - 20", fileName: "c16-20.mp3" },
            { title: "Chương 21 - 25", fileName: "c21-25.mp3" },
            { title: "Chương 26 - 30", fileName: "c26-30.mp3" },
            { title: "Chương 31 - 35", fileName: "c31-35.mp3" },
            { title: "Chương 36 - 40", fileName: "c36-40.mp3" },
            { title: "Chương 41 - 47 (Hết)", fileName: "c41-47.mp3" },
        ]
    },
    {
        id: 7,
        folderName: "DinhCapTenConDo",
        title: "Đỉnh Cấp Tên Côn Đồ (tác giả tạm drop)",
        author: "Chu Phù Yêu",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/DinhCapTenConDo/cover.jpg",
        desc: "Trong một buổi chiều nóng nực. \nChu Hạ Hạ vừa đi học về, cô nhìn thấy một người đàn ông đang đi xuống cầu thang. \nAnh ta rất cao, chân dài, lại cực kì đẹp trai. \nCô lại cảm thấy vô cùng quen mắt, ngập ngừng rồi gọi: “Chú út?”\nChu Dần Khôn đang xắn tay áo che lại vết máu thì nghe thấy ai đó gọi, anh lười biếng nhìn qua. \nỒ, là một cô bé. \nTừ khi nào mà con bé đã lớn như vậy rồi nhỉ?",
        tracks: [
            { title: "Chương 1 - 10", fileName: "c1-10.mp3" },
            { title: "Chương 11 - 20", fileName: "c11-20.mp3" },
            { title: "Chương 21 - 30", fileName: "c21-30.mp3" },
            { title: "Chương 31 - 40", fileName: "c31-40.mp3" },
            { title: "Chương 41 - 50", fileName: "c41-50.mp3" },
            { title: "Chương 51 - 60", fileName: "c51-60.mp3" },
            { title: "Chương 61 - 70", fileName: "c61-70.mp3" },
            { title: "Chương 71 - 80", fileName: "c71-80.mp3" },
            { title: "Chương 81 - 90", fileName: "c81-90.mp3" },
            { title: "Chương 91 - 100", fileName: "c91-100.mp3" },
            { title: "Chương 101 - 110", fileName: "c101-110.mp3" },
            { title: "Chương 111 - 120", fileName: "c111-120.mp3" },
            { title: "Chương 121 - 130", fileName: "c121-130.mp3" },
            { title: "Chương 131 - 140", fileName: "c131-140.mp3" },
            { title: "Chương 141 - 150", fileName: "c141-150.mp3" },
            { title: "Chương 151 - 160", fileName: "c151-160.mp3" },
            { title: "Chương 161 - 170", fileName: "c161-170.mp3" },
            { title: "Chương 171 - 180", fileName: "c171-180.mp3" },
            { title: "Chương 181 - 190", fileName: "c181-190.mp3" },
            { title: "Chương 191 - 200", fileName: "c191-200.mp3" },
            { title: "Chương 201 - 205", fileName: "c201-205.mp3" },
            { title: "Chương 206 - 210", fileName: "c206-210.mp3" },
            { title: "Chương 211 - 215", fileName: "c211-215.mp3" },
            { title: "Chương 216 - 220", fileName: "c216-220.mp3" },
            { title: "Chương 221 - 225", fileName: "c221-225.mp3" },
            { title: "Chương 226 - 230", fileName: "c226-230.mp3" },
            { title: "Chương 231 - 235", fileName: "c231-235.mp3" },
            { title: "Chương 236 - 240", fileName: "c236-240.mp3" },
            { title: "Chương 241 - 245", fileName: "c241-245.mp3" },
            { title: "Chương 246 - 250", fileName: "c246-250.mp3" },
            { title: "Chương 251 - 255", fileName: "c251-255.mp3" },
            { title: "Chương 256 - 260", fileName: "c256-260.mp3" },
            { title: "Chương 261 - 265", fileName: "c261-265.mp3" },
            { title: "Chương 266 - 270", fileName: "c266-270.mp3" },
            { title: "Chương 271 - 275", fileName: "c271-275.mp3" },
            { title: "Chương 276 - 280", fileName: "c276-280.mp3" },
            { title: "Chương 281 - 285", fileName: "c281-285.mp3" },
            { title: "Chương 286 - 290", fileName: "c286-290.mp3" },
            { title: "Chương 291 - 295", fileName: "c291-295.mp3" },
            { title: "Chương 296 - 300", fileName: "c296-300.mp3" },
            { title: "Chương 301 - 305", fileName: "c301-305.mp3" },
            { title: "Chương 306 - 310", fileName: "c306-310.mp3" },
            { title: "Chương 311 - 315", fileName: "c311-315.mp3" },
            { title: "Chương 316 - 320", fileName: "c316-320.mp3" },
            { title: "Chương 321 - 325", fileName: "c321-325.mp3" },
            { title: "Chương 326 - 330", fileName: "c326-330.mp3" },
            { title: "Chương 331 - 335", fileName: "c331-335.mp3" },
            { title: "Chương 336 - 340", fileName: "c336-340.mp3" },
            { title: "Chương 341 - 345", fileName: "c341-345.mp3" },
            { title: "Chương 346 - 350", fileName: "c346-350.mp3" },
            { title: "Chương 351 - 355", fileName: "c351-355.mp3" },
            { title: "Chương 356 - 360", fileName: "c356-360.mp3" },
            { title: "Chương 361 - 365", fileName: "c361-365.mp3" },
            { title: "Chương 366 - 372", fileName: "c366-372.mp3" }            
        ]
    },
    {
        id: 8,
        folderName: "GiayTrangVaThich",
        title: "Giấy Trắng Và Thích",
        author: "Thập Thanh Yểu",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/GiayTrangVaThich/cover.png",
        desc: "Cô không nhớ nhiều chuyện của năm đó, ký ức thanh xuân ngoại trừ anh mà nói đối với cô rất ít.",
        tracks: [
            { title: "Chương 1 - 2 (Hết)", fileName: "c1-2.mp3" },
        ]
    },
    {
        id: 9,
        folderName: "MuonGiong",
        title: "Mượn Giống 1v1",
        author: "Oản Đậu Giáp",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/MuonGiong/cover.jpg",
        desc: "Giới thiệu 1: Vì để thuận lợi kế thừa gia nghiệp, Chu Hạo Cường phát hiện mình không có khả năng sinh đẻ nên đã cố nhịn đưa người vợ yêu quý Tô Đường của mình cho anh trai mình để lấy hạt giống của Chu Sở Thần, người mang dòng máu của nhà họ Chu để sinh ra một đứa con của nhà họ Chu. Tuy nhiên, anh ta đã không ngờ đến đây chỉ là cái bẫy do người khác giăng ra!\n\nGiới thiệu 2: Tô Đường bị người chồng không có khả năng sinh đẻ uy hiếp. Lén lút bò lên giường của anh trai, mượn giống để mang thai. Lần đầu tiên làm loại chuyện này rất do dự, đang muốn từ bỏ trốn chạy lại bị người đàn ông vốn đang bị cho uống thuốc mê ngủ say trên giường đột nhiên xoay người dậy, cơ thể nặng nề đè cô xuống dưới. Hơi thở nóng rực phả tới, giọng nói khàn khàn gọi cô: “Đường Đường, muốn chạy đi đâu?”\n\nTránh mìn: Nữ phi nam xử.",
        tracks: [
            { title: "Chương 1 - 5", fileName: "c1-5.mp3" },
            { title: "Chương 6 - 10", fileName: "c6-10.mp3" },
            { title: "Chương 11 - 15", fileName: "c11-15.mp3" },
            { title: "Chương 16 - 20", fileName: "c16-20.mp3" },
            { title: "Chương 21 - 25", fileName: "c21-25.mp3" },
            { title: "Chương 26 - 30", fileName: "c26-30.mp3" },
            { title: "Chương 31 - 35", fileName: "c31-35.mp3" },
            { title: "Chương 36 - 40", fileName: "c36-40.mp3" },
            { title: "Chương 41 - 45", fileName: "c41-45.mp3" },
            { title: "Chương 46 - 50", fileName: "c46-50.mp3" },
            { title: "Chương 51 - 55", fileName: "c51-55.mp3" },
            { title: "Chương 56 - 60", fileName: "c56-60.mp3" },
            { title: "Chương 61 - 65", fileName: "c61-65.mp3" },
            { title: "Chương 66 - 70", fileName: "c66-70.mp3" },
            { title: "Chương 71 - 75", fileName: "c71-75.mp3" },
            { title: "Chương 76 - 80", fileName: "c76-80.mp3" },
            { title: "Chương 81 - 85", fileName: "c81-85.mp3" },
            { title: "Chương 86 - 90", fileName: "c86-90.mp3" },
            { title: "Chương 91 - 95", fileName: "c91-95.mp3" },
            { title: "Chương 96 - 100", fileName: "c96-100.mp3" },
            { title: "Chương 101 - 105", fileName: "c101-105.mp3" },
            { title: "Chương 106 - 110", fileName: "c106-110.mp3" },
            { title: "Chương 111 - 115", fileName: "c111-115.mp3" },
            { title: "Chương 116 - 120", fileName: "c116-120.mp3" },
            { title: "Chương 121 - 125", fileName: "c121-125.mp3" },
            { title: "Chương 126 - 130", fileName: "c126-130.mp3" },
            { title: "Chương 131 - 135", fileName: "c131-135.mp3" },
            { title: "Chương 136 - 140", fileName: "c136-140.mp3" },
            { title: "Chương 141 - 145", fileName: "c141-145.mp3" },
            { title: "Chương 146 - 150", fileName: "c146-150.mp3" },
            { title: "Chương 151 - 160", fileName: "c151-160.mp3" },  // Bắt đầu khoảng cách 10
            { title: "Chương 161 - 170", fileName: "c161-170.mp3" },
            { title: "Chương 171 - 180", fileName: "c171-180.mp3" },
            { title: "Chương 181 - 190", fileName: "c181-190.mp3" },
            { title: "Chương 191 - 200", fileName: "c191-200.mp3" },
            { title: "Chương 201 - 210", fileName: "c201-210.mp3" },
            { title: "Chương 211 - 220", fileName: "c211-220.mp3" },
            { title: "Chương 221 - 230", fileName: "c221-230.mp3" },
            { title: "Chương 231 - 240", fileName: "c231-240.mp3" },
            { title: "Chương 241 - 250", fileName: "c241-250.mp3" },
            { title: "Chương 251 - 257", fileName: "c251-257.mp3" },
            { title: "Phiên ngoại 1 - 10", fileName: "c258-267.mp3" }, // Bắt đầu Phiên ngoại
            { title: "Phiên ngoại 11 - 20", fileName: "c268-277.mp3" },
            { title: "Phiên ngoại 20 - 30", fileName: "c278-287.mp3" },
            { title: "Phiên ngoại 31 - 38 (Hết)", fileName: "c288-295.mp3" }
        ]
    },
    {
        id: 10,
        folderName: "CaCuoc",
        title: "Cá Cược",
        author: "Mộc Khẩu Ngân",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/CaCuoc/cover.jpg",
        desc: "Lâm Hỉ Triều và Kha Dục vốn là hai cá nhân chẳng có tí liên quan gì với nhau trong trường học.\nCậu là tên công tử nhà giàu nổi loạn, còn cô lại là một học sinh gương mẫu vô danh.\nThế nhưng, sau lưng mọi người, hai người họ luôn tiến hành những cuộc cá cược dựa trên giao dịch thể xác từ nhỏ đến lớn.\nThách cậu giải bài toán đó trong vòng mười phút.\nTôi muốn nụ hôn đầu của cậu.\nĐố cậu buổi tự học tối nay toàn trường có bị mất điện không?\nTôi muốn cậu cởi hết đồ.\nCái thằng hay chuyện với cậu đang thích cậu đúng không?\nTôi muốn cậu, làm tình với tôi, ngay trước mặt nó.",
        tracks: [
            { title: "Chương 1 - 5", fileName: "c1-5.mp3" },
            { title: "Chương 6 - 10", fileName: "c6-10.mp3" },
            { title: "Chương 11 - 15", fileName: "c11-15.mp3" },
            { title: "Chương 16 - 20", fileName: "c16-20.mp3" },
            { title: "Chương 21 - 25", fileName: "c21-25.mp3" },
            { title: "Chương 26 - 30", fileName: "c26-30.mp3" },
            { title: "Chương 31 - 35", fileName: "c31-35.mp3" },
            { title: "Chương 36 - 40", fileName: "c36-40.mp3" },
            { title: "Chương 41 - 45", fileName: "c41-45.mp3" },
            { title: "Chương 46 - 50", fileName: "c46-50.mp3" },
            { title: "Chương 51 - 55", fileName: "c51-55.mp3" },
            { title: "Chương 56 - 60", fileName: "c56-60.mp3" },
            { title: "Chương 61 - 65", fileName: "c61-65.mp3" },
            { title: "Chương 66 - 70", fileName: "c66-70.mp3" },
            { title: "Chương 71 - 75", fileName: "c71-75.mp3" },
            { title: "Chương 76 - 80", fileName: "c76-80.mp3" },
            { title: "Chương 81 - 85", fileName: "c81-85.mp3" },
            { title: "Chương 86 - 90", fileName: "c86-90.mp3" },
            { title: "Chương 91 - 96", fileName: "c91-96.mp3" },
            { title: "Ngoại truyện 1 - 6 (Hết)", fileName: "nt1-6.mp3" }
        ]
    },
    {
        id: 11,
        folderName: "NuPhuTraXanhTroThanhDoChoiCuaNamChinh",
        title: "Nữ Phụ Trà Xanh Trở Thành Đồ Chơi Của Nam Chính",
        author: "Miên Nhuyễn Nhuyễn",
        cover: "https://github.com/truyenhaymoingay2024/sourceTruyen/raw/main/NuPhuTraXanhTroThanhDoChoiCuaNamChinh/cover.jpg",
        desc: "Một câu chuyện khác của nguyên tác “Sau khi bị vả mặt, nữ phụ trèo lên người nam chính (H)”, không còn những tình tiết xuyên sách, đi theo con đường hiện thực tối tăm, tuyến đường cưỡng chế yêu, nhiều H, ngọt ngào.\n\nNữ phụ trà xanh từng bước gặp khó khăn X nam chính không hề che giấu sự ác liệt của mình mà dạo chơi nhân gian.\n\nCô gái đáng thương sinh ra trong gia đình bình thường bị thiếu gia nhà giàu đùa bỡn, thời gian đầu chỉ thích làm tình không thích yêu đương.\n\n“Trà xanh bạch liên”, “tiểu tam”, “tâm cơ”, “quyến rũ Nghiêm Kỷ” đây là những nhãn dán của Mộc Trạch Tê, luôn khiến người ta khinh thường.\n“Học sinh ba tốt”, “nghiêm túc đứng đắn”, “ thân thiện với mọi người “, “dịu dàng” đây là những nhãn dán của Nghiêm Kỷ, được người người khen ngợi.\n\nTừ nhỏ, Mộc Trạch Tê đã có người mẹ luôn mang vọng tưởng bám víu vào những gia đình quyền quý, đương nhiên cô cũng bị dính vào kế hoạch ấy.\nĐể tiếp cận Nghiêm Kỷ, cô dùng đủ mọi cách, thậm chí còn làm khó Lâm Thi Vũ, người tự nhiên thân thiết với Nghiêm Kỷ.\nTất cả những gì cô nhận được cũng chỉ là sự hờ hững và xa cách của Nghiêm Kỷ.\nMộc Trạch Tê từ bỏ...\nDưới lớp ngụy trang của mình, Nghiêm Kỷ là một kẻ vô cùng độc ác. Thái độ của anh với mọi thứ như thần linh dạo chơi nhân gian, sau đó lại nhận ra bản thân mình là kẻ xấu xa, thích làm việc ác nhưng không muốn mình bị mọi người chế nhạo.\nAnh thích kiểm soát và theo đuổi những thứ kích thích.\nKhi phát hiện ra người vẫn luôn theo đuổi mình từ khi còn nhỏ - Mộc Trạch Tê, muốn chạy sang vòng tay của kẻ khác, anh phát điên lên. Sau khi ăn sạch người ta vào miệng, anh ăn tủy biết vị [1] phát hiện niềm vui sướng mỗi khi đùa bỡn Mộc Trạch Tê.\nMộc Trạch Tê vẫn luôn dựa vào dáng người của mình để quyến rũ được Nghiêm Kỷ, giúp mẹ cô có thể từng bước tiến vào nhà họ Nghiêm giàu sang, quyền thế.\nNhưng chỉ có mình Mộc Trạch Tê biết được, đằng sau nét cười ôn hòa là sự u tối chỉ biết làm tình của anh.\nĐây là câu chuyện nguyên bản của “Sau khi bị vả mặt nữ phụ trèo cao có được nam chính (H)”.\nLà một câu chuyện thể hiện ý chí của một người phụ nữ chỉ có nhan sắc nhưng lại muốn leo lên một gia đình giàu có, lấy nhan sắc để phục vụ dục vọng của người khác. (Hai người có tình cảm, nhưng không cản trở nam chính ham mê nữ sắc, vẫn chóa lắm).\nNếu không thích, thì nhanh chạy!.\nBởi vì là một câu chuyện khác nên sẽ có cảnh mới, cũng sẽ có một số cảnh và văn bản là trong “Nữ phụ vả mặt”. Chuyện nguyên bản, cùng một cảnh tượng nhưng câu chuyện khác nhau.\nTính cách của nhân vật cơ bản không thay đổi, nhưng nội dung cốt truyện sẽ đi theo hướng khác.",
        tracks: [
            { title: "Chương 1 - 5", fileName: "c1-5.m4a" },
            { title: "Chương 6 - 10", fileName: "c6-10.m4a" },
            { title: "Chương 11 - 15", fileName: "c11-15.m4a" },
            { title: "Chương 16 - 20", fileName: "c16-20.m4a" },
            { title: "Chương 21 - 25", fileName: "c21-25.m4a" },
            { title: "Chương 26 - 30", fileName: "c26-30.m4a" },
            { title: "Chương 31 - 35", fileName: "c31-35.m4a" },
            { title: "Chương 36 - 40", fileName: "c36-40.m4a" },
            { title: "Chương 41 - 45", fileName: "c41-45.m4a" },
            { title: "Chương 46 - 50", fileName: "c46-50.m4a" },
            { title: "Chương 51 - 55", fileName: "c51-55.m4a" },
            { title: "Chương 56 - 60", fileName: "c56-60.m4a" },
            { title: "Chương 61 - 64 (Hết)", fileName: "c61-64.m4a" }
        ]
    },
];
